name: DMWrapper
main: me.slaps.DMWrapper.DMWrapper
version: 0.04
author: magik
description: >
             Wrapper for DynamicMarket that adds location features.
commands:
    dshop:
       description: Accesses the shop command system.
       aliases: shop
       usage: |
              /<command>
              /<command> help <topic/command>
              /<command> <itemid>
              /<command> <subcommand> <args>               